name: ğŸš€ CD - Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ·ï¸ Check out Git repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: ğŸ“¦ Build docs application
        working-directory: ./docs
        run: npm install --force && npm run build

      - name: ğŸ“¦ Build landing-page application
        working-directory: ./www
        run: npm install --force && npm run build && npm run export

      - name: ğŸ“¦ Build marketplace application
        working-directory: ./marketplace
        run: npm install --force && npm run build && npm run export

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_FONOSTER_WEBSITE }}'
          channelId: live
          projectId: fonoster-website
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
